# Generated by Django 2.0 on 2018-02-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal', '0002_remove_animes_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animes',
            options={'verbose_name': 'Anime', 'verbose_name_plural': 'Animes'},
        ),
        migrations.AddField(
            model_name='animes',
            name='status',
            field=models.CharField(choices=[('ja', 'ja assisti'), ('qa', 'Quero assistir'), ('ea', 'Estou assistindo')], default='qa', max_length=264),
        ),
    ]
