# Generated by Django 2.0 on 2018-03-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal', '0003_auto_20180228_1255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animes',
            unique_together={('topic', 'name')},
        ),
    ]
