# Generated by Django 2.0 on 2018-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal', '0004_auto_20180307_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
