# Generated by Django 2.0 on 2018-03-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal', '0005_auto_20180307_1756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animes',
            unique_together=set(),
        ),
    ]
