# Generated by Django 2.0 on 2018-03-08 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mal', '0007_auto_20180307_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
