# Generated by Django 2.0 on 2018-03-08 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mal', '0008_topic_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='animes',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
